// This file is auto-generated by flutterfire configure
// Run: flutterfire configure --project=your-firebase-project-id

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlguBd5PseUeM36BC0nWnC3J5WEZgB2rM',
    appId: '1:968487337580:web:4b722b9e5d75255cb3a249',
    messagingSenderId: '968487337580',
    projectId: 'rtae-6211e',
    authDomain: 'rtae-6211e.firebaseapp.com',
    storageBucket: 'rtae-6211e.firebasestorage.app',
  );
}
